function customMain()
    preloadAngles(Bird:loadAngles())
    Bird:initIdleModels()
    BlzLoadTOCFile("framedef\\flappybird.toc")
    initSounds()
    Game.init()
    SetGameSpeed(MAP_SPEED_FASTEST)
    TimerStart(CreateTimer(), 0, false, function()
        setMenuTransparent()
        setTitleHeight()
        Game.start()
        DestroyTimer(GetExpiredTimer())
    end)
end